"""Initial migration DB changer

Revision ID: e6efd3a93885
Revises: None
Create Date: 2016-04-08 22:25:59.004430

"""

# revision identifiers, used by Alembic.
revision = 'e6efd3a93885'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_collector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('date_operation', sa.DateTime(), nullable=True),
    sa.Column('oper_id', sa.Integer(), nullable=True),
    sa.Column('count_uah', sa.Float(), nullable=True),
    sa.Column('count_usd', sa.Float(), nullable=True),
    sa.Column('count_eur', sa.Float(), nullable=True),
    sa.Column('count_rub', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oper_id'], ['type_of_operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_collector')
    ### end Alembic commands ###
